name: Flake8 Python Linter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with Flake8
      run: |
        # stop the build if there are errors
        flake8 . --count --show-source --statistics --max-line-length=120
